name: brick_lib
description: Base lib for Brick Converter and Brick Collector Apps
version: 0.0.4
publish_to: none
homepage:

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2


  logger: 1.1.0

  json_annotation: ^4.4.0

  file_picker: ^5.2.5

  get_it: ^7.2.0
  get_it_mixin: ^3.1.4
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  flutter_native_splash: ^2.2.17
  dio: ^4.0.6

  intl: ^0.17.0

  flutter_slidable: ^2.0.0

  url_launcher: ^6.1.8
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.1.7
  json_serializable: ^6.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: de.fpe.brick_lib
        pluginClass: BrickLibPlugin
      ios:
        pluginClass: BrickLibPlugin
      linux:
        pluginClass: BrickLibPlugin
      macos:
        pluginClass: BrickLibPlugin
      windows:
        pluginClass: BrickLibPluginCApi
      web:
        pluginClass: BrickLibWeb
        fileName: brick_lib_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/color_table.csv
    - assets/gobrick_conversion_table.csv
    - #   - images/a_dot_burr.jpeg
      #   - images/a_dot_ham.jpeg
      #
      # For details regarding assets in packages, see
      # https://flutter.dev/assets-and-images/#from-packages
      #
      # An image asset can refer to one or more resolution-specific "variants", see
      # https://flutter.dev/assets-and-images/#resolution-aware

      # To add custom fonts to your plugin package, add a fonts section here,
      # in this "flutter" section. Each entry in this list should have a
      # "family" key with the font family name, and a "fonts" key with a
      # list giving the asset and other descriptors for the font. For
      # example:
      # fonts:
      #   - family: Schyler
      #     fonts:
      #       - asset: fonts/Schyler-Regular.ttf
      #       - asset: fonts/Schyler-Italic.ttf
      #         style: italic
      #   - family: Trajan Pro
      #     fonts:
      #       - asset: fonts/TrajanPro.ttf
      #       - asset: fonts/TrajanPro_Bold.ttf
      #         weight: 700
      #
      # For details regarding fonts in packages, see
    # https://flutter.dev/custom-fonts/#from-packages
