// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'brick_color.freezed.dart';

// optional: Since our BrickColor class is serializable, we must add this line.
// But if BrickColor was not serializable, we could skip it.
part 'brick_color.g.dart';

@freezed
class BrickColor with _$BrickColor {
  const factory BrickColor({
    required String legoColor,
    required String bricklinkColor,
    required String rebrickableColor,
    required String goBrickColor,
    required String lddName,
    required String name,
    required String rgb,
  }) = _BrickColor;

  factory BrickColor.fromJson(Map<String, Object?> json) => _$BrickColorFromJson(json);
}
